name: Appium CI
on:
  push:
    branches: [ research/automation_tests ]

jobs:
  e2e:
    runs-on: self-hosted
    environment: CI
    name: Appium Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Android Apps
        run: ./gradlew assemble
      - name: Run Appium Server
        run: |
          appium --allow-insecure chromedriver_autodownload &
      - name: Run Instrumented tests
        run: |
          emulator @Secondary -no-window -no-snapshot -noaudio -no-boot-anim &
          adb wait-for-device
          ./gradlew installDebug
          ./gradlew connectedCheck