name: Appium CI
on:
  push:
    branches: [ research/automation_tests ]

jobs:
  e2e:
    runs-on: self-hosted
    environment: CI
    name: Appium Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Android Apps
        run: ./gradlew assemble
      - name: Run Appium Server
        run: appium --allow-insecure chromedriver_autodownload &
      - name: Run Emulator
        run: |
          $ANDROID_HOME/emulator/emulator @Secondary -no-window -no-snapshot -noaudio -no-boot-anim &
          $ANDROID_HOME/platform-tools/adb wait-for-device
      - name: Install Sample Apps
        run: ./gradlew installDebug
      - name: Run Instrumented Tests
        run: ./gradlew connectedCheck